/*
	This file is generated by net_compiler.py.
	The use of included functions list as follows:

	Input:
	inferx_input(int *shape, void *pdata, char *top,char *name,char *model_pre,char *data_pre,struct inferx_handler *hd)
	

	Convolution:
	inferx_convolution(int num_input,int num_output,int kernel_h,int kernel_w,int stride_h,int stride_w,int pad_h,int pad_w,int group,int dilation,int axis,bool bias_term,bool force_nd_im2col,char *bottom,char *top, char *name,char *model_pre, char *data_pre, int activation_type, float negative_slope, struct inferx_handler *hd)
	

	BatchNorm:
	inferx_batchnorm(float moving_average_fraction,float eps,bool use_global_stats,char *bottom,char *top,char *name, char *model_pre, char *data_pre, struct inferx_handler *hd)

	Scale:
	inferx_scale(int axis,int num_axes,bool bias_term,char *bottom,char *top,char *name, char *model_pre, char *data_pre, struct inferx_handler *hd)

	ReLU:
	inferx_relu(float slope, char *bottom,char *top,char *name, char *model_pre, char *data_pre, struct inferx_handler *hd)
*/


#include "interface.h"
#include <stdbool.h>
struct inferx_handler;
void FaceNetNew(char* path, char* model, char* data, int *shape, int nshape, void* pdata, void** pout,int *len, struct inferx_handler *hd)
{
	inferx_net_preprocess(data,model,hd);

	inferx_input(shape,pdata,"data_data","data",model,data,hd);
	inferx_convolution(1,8,5,5,2,2,2,2,1,1,1,true,false,"data_data","L0_scale_data","L0",model,data, 1, 0.0, hd);
	inferx_convolution(8,16,5,5,2,2,2,2,1,1,1,true,false,"L0_scale_data","L0_1_scale_data","L0_1",model,data, 1, 0.0, hd);
	inferx_convolution(16,16,3,3,2,2,1,1,1,1,1,true,false,"L0_1_scale_data","cp1_scale_data","cp1",model,data, 1, 0.0, hd);
	inferx_convolution(16,32,5,5,1,1,2,2,1,1,1,true,false,"cp1_scale_data","L1_scale_data","L1",model,data, 1, 0.0, hd);
	inferx_convolution(32,32,3,3,2,2,1,1,1,1,1,true,false,"L1_scale_data","cp2_scale_data","cp2",model,data, 1, 0.0, hd);
	inferx_convolution(32,48,3,3,1,1,1,1,1,1,1,true,false,"cp2_scale_data","L2_scale_data","L2",model,data, 1, 0.0, hd);
	inferx_convolution(48,48,3,3,1,1,1,1,1,1,1,true,false,"L2_scale_data","L3_scale_data","L3",model,data, 1, 0.0, hd);
	inferx_convolution(48,64,3,3,1,1,1,1,1,1,1,true,false,"L3_scale_data","L4_scale_data","L4",model,data, 1, 0.0, hd);
	inferx_convolution(64,64,3,3,2,2,1,1,1,1,1,true,false,"L4_scale_data","cp5_scale_data","cp5",model,data, 1, 0.0, hd);
	inferx_convolution(64,128,5,5,1,1,2,2,1,1,1,true,false,"cp5_scale_data","L5_scale_data","L5",model,data, 1, 0.0, hd);
	inferx_convolution(128,128,1,1,1,1,0,0,1,1,1,true,false,"L5_scale_data","L6_scale_data","L6",model,data, 1, 0.0, hd);
	inferx_convolution(128,256,1,1,1,1,0,0,1,1,1,true,false,"L6_scale_data","bb-output_data","bb-output",model,data, 0, 0, hd);
	inferx_convolution(128,128,1,1,1,1,0,0,1,1,1,true,false,"L6_scale_data","pixel-conv_data","pixel-conv",model,data, 0, 0, hd);

	// only one output feature map 
	//inferx_sort_data("pixel-conv_data",data);
	//inferx_print_data("pixel-conv_data",data);
	//if(pout)
	  //*pout = inferx_get_data("pixel-conv_data",data,len,hd);
	inferx_finalize("FaceNetNew",hd);

	return;
}
