/*
	This file is generated by net_compiler.py.
	The use of included functions list as follows:

	Input:
	inferx_input(int *shape, void *pdata, char *top,char *name,char *model_pre,char *data_pre,struct inferx_handler *hd)
	

	Convolution:
	inferx_convolution(int num_input,int num_output,int kernel_h,int kernel_w,int stride_h,int stride_w,int pad_h,int pad_w,int group,int dilation,int axis,bool bias_term,bool force_nd_im2col,char *bottom,char *top, char *name,char *model_pre, char *data_pre, int activation_type, float negative_slope, struct inferx_handler *hd)
	

	PReLU:
	inferx_prelu(int shared_channels, float default_slope, char* bottom_pre, char* top_pre, char* iname_pre, char *model_pre, char *data_pre, struct inferx_handler *hd)

	BatchNorm:
	inferx_batchnorm(float moving_average_fraction,float eps,bool use_global_stats,char *bottom,char *top,char *name, char *model_pre, char *data_pre, struct inferx_handler *hd)

	Scale:
	inferx_scale(int axis,int num_axes,bool bias_term,char *bottom,char *top,char *name, char *model_pre, char *data_pre, struct inferx_handler *hd)

	Eltwise:
	inferx_elem_wise_operate(int coeffs_num, float* coeffs, char* op_mode,bool stabel_prod_grad,int bottom_num,char **bottoms,char *top, char *name, char *model_pre, char *data_pre, struct inferx_handler *hd)
	

	InnerProduct:
	inferx_inner_product(int num_input,int num_output,bool bias_term,bool transpose,char *bottom,char *top,char *name,char *model_pre, char *data_pre, struct inferx_handler *hd)
*/


#include "interface.h"
#include <stdbool.h>
struct inferx_handler;
void resnet84(char* path, char* model, char* data, int *shape, int nshape, void* pdata, void** pout,int *len, struct inferx_handler *hd)
{
	float coeffs[2];
	char* bottom_vector[2];

	inferx_net_preprocess(data,model,hd);

	inferx_input(shape,pdata,"data_data","data",model,data,hd);
	inferx_convolution(3,16,3,3,2,2,1,1,1,1,1,true,false,"data_data","ConvNd_1_data","ConvNd_1",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"ConvNd_1_data","PReLU_1_data","PReLU_1",model,data,hd);
	inferx_convolution(16,16,3,3,1,1,1,1,1,1,1,true,false,"PReLU_1_data","BatchNorm_1_data","ConvNd_2",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_1_data","PReLU_2_data","PReLU_2",model,data,hd);
	inferx_convolution(16,16,3,3,1,1,1,1,1,1,1,true,false,"PReLU_2_data","BatchNorm_2_data","ConvNd_3",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_2_data";	bottom_vector[1] = "PReLU_1_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_1_data","Add_1",model,data,hd);
	inferx_prelu(0,0.1,"Add_1_data","PReLU_3_data","PReLU_3",model,data,hd);
	inferx_convolution(16,16,3,3,1,1,1,1,1,1,1,true,false,"PReLU_3_data","BatchNorm_3_data","ConvNd_4",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_3_data","PReLU_4_data","PReLU_4",model,data,hd);
	inferx_convolution(16,16,3,3,1,1,1,1,1,1,1,true,false,"PReLU_4_data","BatchNorm_4_data","ConvNd_5",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_4_data";	bottom_vector[1] = "PReLU_3_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_2_data","Add_2",model,data,hd);
	inferx_prelu(0,0.1,"Add_2_data","PReLU_5_data","PReLU_5",model,data,hd);
	inferx_convolution(16,16,3,3,1,1,1,1,1,1,1,true,false,"PReLU_5_data","BatchNorm_5_data","ConvNd_6",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_5_data","PReLU_6_data","PReLU_6",model,data,hd);
	inferx_convolution(16,16,3,3,1,1,1,1,1,1,1,true,false,"PReLU_6_data","BatchNorm_6_data","ConvNd_7",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_6_data";	bottom_vector[1] = "PReLU_5_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_3_data","Add_3",model,data,hd);
	inferx_prelu(0,0.1,"Add_3_data","PReLU_7_data","PReLU_7",model,data,hd);
	inferx_convolution(16,16,3,3,1,1,1,1,1,1,1,true,false,"PReLU_7_data","BatchNorm_7_data","ConvNd_8",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_7_data","PReLU_8_data","PReLU_8",model,data,hd);
	inferx_convolution(16,16,3,3,1,1,1,1,1,1,1,true,false,"PReLU_8_data","BatchNorm_8_data","ConvNd_9",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_8_data";	bottom_vector[1] = "PReLU_7_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_4_data","Add_4",model,data,hd);
	inferx_prelu(0,0.1,"Add_4_data","PReLU_9_data","PReLU_9",model,data,hd);
	inferx_convolution(16,32,3,3,2,2,1,1,1,1,1,true,false,"PReLU_9_data","ConvNd_10_data","ConvNd_10",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"ConvNd_10_data","PReLU_10_data","PReLU_10",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_10_data","BatchNorm_9_data","ConvNd_11",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_9_data","PReLU_11_data","PReLU_11",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_11_data","BatchNorm_10_data","ConvNd_12",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_10_data";	bottom_vector[1] = "PReLU_10_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_5_data","Add_5",model,data,hd);
	inferx_prelu(0,0.1,"Add_5_data","PReLU_12_data","PReLU_12",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_12_data","BatchNorm_11_data","ConvNd_13",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_11_data","PReLU_13_data","PReLU_13",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_13_data","BatchNorm_12_data","ConvNd_14",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_12_data";	bottom_vector[1] = "PReLU_12_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_6_data","Add_6",model,data,hd);
	inferx_prelu(0,0.1,"Add_6_data","PReLU_14_data","PReLU_14",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_14_data","BatchNorm_13_data","ConvNd_15",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_13_data","PReLU_15_data","PReLU_15",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_15_data","BatchNorm_14_data","ConvNd_16",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_14_data";	bottom_vector[1] = "PReLU_14_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_7_data","Add_7",model,data,hd);
	inferx_prelu(0,0.1,"Add_7_data","PReLU_16_data","PReLU_16",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_16_data","BatchNorm_15_data","ConvNd_17",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_15_data","PReLU_17_data","PReLU_17",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_17_data","BatchNorm_16_data","ConvNd_18",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_16_data";	bottom_vector[1] = "PReLU_16_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_8_data","Add_8",model,data,hd);
	inferx_prelu(0,0.1,"Add_8_data","PReLU_18_data","PReLU_18",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_18_data","BatchNorm_17_data","ConvNd_19",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_17_data","PReLU_19_data","PReLU_19",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_19_data","BatchNorm_18_data","ConvNd_20",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_18_data";	bottom_vector[1] = "PReLU_18_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_9_data","Add_9",model,data,hd);
	inferx_prelu(0,0.1,"Add_9_data","PReLU_20_data","PReLU_20",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_20_data","BatchNorm_19_data","ConvNd_21",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_19_data","PReLU_21_data","PReLU_21",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_21_data","BatchNorm_20_data","ConvNd_22",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_20_data";	bottom_vector[1] = "PReLU_20_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_10_data","Add_10",model,data,hd);
	inferx_prelu(0,0.1,"Add_10_data","PReLU_22_data","PReLU_22",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_22_data","BatchNorm_21_data","ConvNd_23",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_21_data","PReLU_23_data","PReLU_23",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_23_data","BatchNorm_22_data","ConvNd_24",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_22_data";	bottom_vector[1] = "PReLU_22_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_11_data","Add_11",model,data,hd);
	inferx_prelu(0,0.1,"Add_11_data","PReLU_24_data","PReLU_24",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_24_data","BatchNorm_23_data","ConvNd_25",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_23_data","PReLU_25_data","PReLU_25",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_25_data","BatchNorm_24_data","ConvNd_26",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_24_data";	bottom_vector[1] = "PReLU_24_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_12_data","Add_12",model,data,hd);
	inferx_prelu(0,0.1,"Add_12_data","PReLU_26_data","PReLU_26",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_26_data","BatchNorm_25_data","ConvNd_27",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_25_data","PReLU_27_data","PReLU_27",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_27_data","BatchNorm_26_data","ConvNd_28",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_26_data";	bottom_vector[1] = "PReLU_26_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_13_data","Add_13",model,data,hd);
	inferx_prelu(0,0.1,"Add_13_data","PReLU_28_data","PReLU_28",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_28_data","BatchNorm_27_data","ConvNd_29",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_27_data","PReLU_29_data","PReLU_29",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_29_data","BatchNorm_28_data","ConvNd_30",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_28_data";	bottom_vector[1] = "PReLU_28_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_14_data","Add_14",model,data,hd);
	inferx_prelu(0,0.1,"Add_14_data","PReLU_30_data","PReLU_30",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_30_data","BatchNorm_29_data","ConvNd_31",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_29_data","PReLU_31_data","PReLU_31",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_31_data","BatchNorm_30_data","ConvNd_32",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_30_data";	bottom_vector[1] = "PReLU_30_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_15_data","Add_15",model,data,hd);
	inferx_prelu(0,0.1,"Add_15_data","PReLU_32_data","PReLU_32",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_32_data","BatchNorm_31_data","ConvNd_33",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_31_data","PReLU_33_data","PReLU_33",model,data,hd);
	inferx_convolution(32,32,3,3,1,1,1,1,1,1,1,true,false,"PReLU_33_data","BatchNorm_32_data","ConvNd_34",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_32_data";	bottom_vector[1] = "PReLU_32_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_16_data","Add_16",model,data,hd);
	inferx_prelu(0,0.1,"Add_16_data","PReLU_34_data","PReLU_34",model,data,hd);
	inferx_convolution(32,64,3,3,2,2,1,1,1,1,1,true,false,"PReLU_34_data","ConvNd_35_data","ConvNd_35",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"ConvNd_35_data","PReLU_35_data","PReLU_35",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_35_data","BatchNorm_33_data","ConvNd_36",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_33_data","PReLU_36_data","PReLU_36",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_36_data","BatchNorm_34_data","ConvNd_37",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_34_data";	bottom_vector[1] = "PReLU_35_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_17_data","Add_17",model,data,hd);
	inferx_prelu(0,0.1,"Add_17_data","PReLU_37_data","PReLU_37",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_37_data","BatchNorm_35_data","ConvNd_38",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_35_data","PReLU_38_data","PReLU_38",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_38_data","BatchNorm_36_data","ConvNd_39",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_36_data";	bottom_vector[1] = "PReLU_37_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_18_data","Add_18",model,data,hd);
	inferx_prelu(0,0.1,"Add_18_data","PReLU_39_data","PReLU_39",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_39_data","BatchNorm_37_data","ConvNd_40",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_37_data","PReLU_40_data","PReLU_40",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_40_data","BatchNorm_38_data","ConvNd_41",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_38_data";	bottom_vector[1] = "PReLU_39_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_19_data","Add_19",model,data,hd);
	inferx_prelu(0,0.1,"Add_19_data","PReLU_41_data","PReLU_41",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_41_data","BatchNorm_39_data","ConvNd_42",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_39_data","PReLU_42_data","PReLU_42",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_42_data","BatchNorm_40_data","ConvNd_43",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_40_data";	bottom_vector[1] = "PReLU_41_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_20_data","Add_20",model,data,hd);
	inferx_prelu(0,0.1,"Add_20_data","PReLU_43_data","PReLU_43",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_43_data","BatchNorm_41_data","ConvNd_44",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_41_data","PReLU_44_data","PReLU_44",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_44_data","BatchNorm_42_data","ConvNd_45",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_42_data";	bottom_vector[1] = "PReLU_43_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_21_data","Add_21",model,data,hd);
	inferx_prelu(0,0.1,"Add_21_data","PReLU_45_data","PReLU_45",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_45_data","BatchNorm_43_data","ConvNd_46",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_43_data","PReLU_46_data","PReLU_46",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_46_data","BatchNorm_44_data","ConvNd_47",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_44_data";	bottom_vector[1] = "PReLU_45_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_22_data","Add_22",model,data,hd);
	inferx_prelu(0,0.1,"Add_22_data","PReLU_47_data","PReLU_47",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_47_data","BatchNorm_45_data","ConvNd_48",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_45_data","PReLU_48_data","PReLU_48",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_48_data","BatchNorm_46_data","ConvNd_49",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_46_data";	bottom_vector[1] = "PReLU_47_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_23_data","Add_23",model,data,hd);
	inferx_prelu(0,0.1,"Add_23_data","PReLU_49_data","PReLU_49",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_49_data","BatchNorm_47_data","ConvNd_50",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_47_data","PReLU_50_data","PReLU_50",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_50_data","BatchNorm_48_data","ConvNd_51",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_48_data";	bottom_vector[1] = "PReLU_49_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_24_data","Add_24",model,data,hd);
	inferx_prelu(0,0.1,"Add_24_data","PReLU_51_data","PReLU_51",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_51_data","BatchNorm_49_data","ConvNd_52",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_49_data","PReLU_52_data","PReLU_52",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_52_data","BatchNorm_50_data","ConvNd_53",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_50_data";	bottom_vector[1] = "PReLU_51_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_25_data","Add_25",model,data,hd);
	inferx_prelu(0,0.1,"Add_25_data","PReLU_53_data","PReLU_53",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_53_data","BatchNorm_51_data","ConvNd_54",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_51_data","PReLU_54_data","PReLU_54",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_54_data","BatchNorm_52_data","ConvNd_55",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_52_data";	bottom_vector[1] = "PReLU_53_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_26_data","Add_26",model,data,hd);
	inferx_prelu(0,0.1,"Add_26_data","PReLU_55_data","PReLU_55",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_55_data","BatchNorm_53_data","ConvNd_56",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_53_data","PReLU_56_data","PReLU_56",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_56_data","BatchNorm_54_data","ConvNd_57",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_54_data";	bottom_vector[1] = "PReLU_55_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_27_data","Add_27",model,data,hd);
	inferx_prelu(0,0.1,"Add_27_data","PReLU_57_data","PReLU_57",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_57_data","BatchNorm_55_data","ConvNd_58",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_55_data","PReLU_58_data","PReLU_58",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_58_data","BatchNorm_56_data","ConvNd_59",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_56_data";	bottom_vector[1] = "PReLU_57_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_28_data","Add_28",model,data,hd);
	inferx_prelu(0,0.1,"Add_28_data","PReLU_59_data","PReLU_59",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_59_data","BatchNorm_57_data","ConvNd_60",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_57_data","PReLU_60_data","PReLU_60",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_60_data","BatchNorm_58_data","ConvNd_61",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_58_data";	bottom_vector[1] = "PReLU_59_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_29_data","Add_29",model,data,hd);
	inferx_prelu(0,0.1,"Add_29_data","PReLU_61_data","PReLU_61",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_61_data","BatchNorm_59_data","ConvNd_62",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_59_data","PReLU_62_data","PReLU_62",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_62_data","BatchNorm_60_data","ConvNd_63",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_60_data";	bottom_vector[1] = "PReLU_61_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_30_data","Add_30",model,data,hd);
	inferx_prelu(0,0.1,"Add_30_data","PReLU_63_data","PReLU_63",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_63_data","BatchNorm_61_data","ConvNd_64",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_61_data","PReLU_64_data","PReLU_64",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_64_data","BatchNorm_62_data","ConvNd_65",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_62_data";	bottom_vector[1] = "PReLU_63_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_31_data","Add_31",model,data,hd);
	inferx_prelu(0,0.1,"Add_31_data","PReLU_65_data","PReLU_65",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_65_data","BatchNorm_63_data","ConvNd_66",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_63_data","PReLU_66_data","PReLU_66",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_66_data","BatchNorm_64_data","ConvNd_67",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_64_data";	bottom_vector[1] = "PReLU_65_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_32_data","Add_32",model,data,hd);
	inferx_prelu(0,0.1,"Add_32_data","PReLU_67_data","PReLU_67",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_67_data","BatchNorm_65_data","ConvNd_68",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_65_data","PReLU_68_data","PReLU_68",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_68_data","BatchNorm_66_data","ConvNd_69",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_66_data";	bottom_vector[1] = "PReLU_67_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_33_data","Add_33",model,data,hd);
	inferx_prelu(0,0.1,"Add_33_data","PReLU_69_data","PReLU_69",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_69_data","BatchNorm_67_data","ConvNd_70",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_67_data","PReLU_70_data","PReLU_70",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_70_data","BatchNorm_68_data","ConvNd_71",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_68_data";	bottom_vector[1] = "PReLU_69_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_34_data","Add_34",model,data,hd);
	inferx_prelu(0,0.1,"Add_34_data","PReLU_71_data","PReLU_71",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_71_data","BatchNorm_69_data","ConvNd_72",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_69_data","PReLU_72_data","PReLU_72",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_72_data","BatchNorm_70_data","ConvNd_73",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_70_data";	bottom_vector[1] = "PReLU_71_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_35_data","Add_35",model,data,hd);
	inferx_prelu(0,0.1,"Add_35_data","PReLU_73_data","PReLU_73",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_73_data","BatchNorm_71_data","ConvNd_74",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_71_data","PReLU_74_data","PReLU_74",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"PReLU_74_data","BatchNorm_72_data","ConvNd_75",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_72_data";	bottom_vector[1] = "PReLU_73_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_36_data","Add_36",model,data,hd);
	inferx_prelu(0,0.1,"Add_36_data","PReLU_75_data","PReLU_75",model,data,hd);
	inferx_convolution(64,128,3,3,2,2,1,1,1,1,1,true,false,"PReLU_75_data","ConvNd_76_data","ConvNd_76",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"ConvNd_76_data","PReLU_76_data","PReLU_76",model,data,hd);
	inferx_convolution(128,128,3,3,1,1,1,1,1,1,1,true,false,"PReLU_76_data","BatchNorm_73_data","ConvNd_77",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_73_data","PReLU_77_data","PReLU_77",model,data,hd);
	inferx_convolution(128,128,3,3,1,1,1,1,1,1,1,true,false,"PReLU_77_data","BatchNorm_74_data","ConvNd_78",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_74_data";	bottom_vector[1] = "PReLU_76_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_37_data","Add_37",model,data,hd);
	inferx_prelu(0,0.1,"Add_37_data","PReLU_78_data","PReLU_78",model,data,hd);
	inferx_convolution(128,128,3,3,1,1,1,1,1,1,1,true,false,"PReLU_78_data","BatchNorm_75_data","ConvNd_79",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_75_data","PReLU_79_data","PReLU_79",model,data,hd);
	inferx_convolution(128,128,3,3,1,1,1,1,1,1,1,true,false,"PReLU_79_data","BatchNorm_76_data","ConvNd_80",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_76_data";	bottom_vector[1] = "PReLU_78_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_38_data","Add_38",model,data,hd);
	inferx_prelu(0,0.1,"Add_38_data","PReLU_80_data","PReLU_80",model,data,hd);
	inferx_convolution(128,128,3,3,1,1,1,1,1,1,1,true,false,"PReLU_80_data","BatchNorm_77_data","ConvNd_81",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_77_data","PReLU_81_data","PReLU_81",model,data,hd);
	inferx_convolution(128,128,3,3,1,1,1,1,1,1,1,true,false,"PReLU_81_data","BatchNorm_78_data","ConvNd_82",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_78_data";	bottom_vector[1] = "PReLU_80_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_39_data","Add_39",model,data,hd);
	inferx_prelu(0,0.1,"Add_39_data","PReLU_82_data","PReLU_82",model,data,hd);
	inferx_convolution(128,128,3,3,1,1,1,1,1,1,1,true,false,"PReLU_82_data","BatchNorm_79_data","ConvNd_83",model,data, 0, 0, hd);
	inferx_prelu(0,0.1,"BatchNorm_79_data","PReLU_83_data","PReLU_83",model,data,hd);
	inferx_convolution(128,128,3,3,1,1,1,1,1,1,1,true,false,"PReLU_83_data","BatchNorm_80_data","ConvNd_84",model,data, 0, 0, hd);
	bottom_vector[0] = "BatchNorm_80_data";	bottom_vector[1] = "PReLU_82_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_elem_wise_operate(2,coeffs,"SUM",true,2,bottom_vector,"Add_40_data","Add_40",model,data,hd);
	inferx_prelu(0,0.1,"Add_40_data","PReLU_84_data","PReLU_84",model,data,hd);
	inferx_batchnorm(0.999,9.99999974738e-06,true,"PReLU_84_data","BatchNorm_81_data","BatchNorm_81",model,data,hd);
	inferx_scale(1,1,true,"BatchNorm_81_data","BatchNorm_81_data","BatchNorm_81_scale",model,data,hd);
	inferx_inner_product(128,512,false,false,"BatchNorm_81_data","Addmm_1_data","Addmm_1",model,data,hd);
	inferx_batchnorm(0.999,9.99999974738e-06,true,"Addmm_1_data","BatchNorm_82_data","BatchNorm_82",model,data,hd);
	inferx_scale(1,1,false,"BatchNorm_82_data","BatchNorm_82_data","BatchNorm_82_scale",model,data,hd);

	// only one output feature map 
	//inferx_sort_data("BatchNorm_82_data",data);
	//inferx_print_data("BatchNorm_82_data",data);
	//if(pout)
	  //*pout = inferx_get_data("BatchNorm_82_data",data,len,hd);
	inferx_finalize("resnet84",hd);

	return;
}
